#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


/usr/bin/env java -cp $DIR/alamode.jar com.htssoft.alamode.IndexUtility $@
/usr/bin/env java -cp $DIR/alamode.jar com.htssoft.alamode.files.FileHasher alamode.index > version

